### ISSUE TITLE
Code on chinese dataset TableQA

### ISSUE THREAD

**Issue by zyzsixsixsix** [lyuqin/HydraNet-WikiSQL#12]
a lot of papers show the results of HydraNet on Chinese dataset--TableQA，I want to ask if you have the code on Chinese datasets.Or do you kown how the paper get the results? Change the code by themselves or others?
Thank you!

**Comment by lyuqin** [comment]
In fact I am not aware of HydraNet being applied to other dataset, but I'm really happy to know that! I haven't tried HydraNet on other dataset, but I think if one can transform the dataset into WikiSQL format, then the same training/evaluation process can be directly applied

**Comment by xwt0016** [comment]
> a lot of papers show the results of HydraNet on Chinese dataset--TableQA，I want to ask if you have the code on Chinese datasets.Or do you kown how the paper get the results? Change the code by themselves or others? Thank you!
您好，能告知一下哪些论文汇报了hydranet在tableqa上的准确率吗
