### ISSUE TITLE
How to use other pretrain model in this code?

### ISSUE THREAD

**Issue by chaser-girl** [lyuqin/HydraNet-WikiSQL#15]
Hello! I want to use some other model as for base model. For some commen models such as bert that it is easy to work. So if j just have .pt and source code ,how do i put it into utils.py-->create_base_mode(config) ? if there will have some data format question in these process？

I want to use mt-dnn for the base model and just have .pt. i'm very hope for you help! Thanks！

**Comment by chaser-girl** [comment]
Dose it only use torch.load() to do this? or need i correct the data format same as hydranet?

**Comment by lyuqin** [comment]
Our code uses Huggingface transformers API to load pretrained model and tokenizer:
https://github.com/lyuqin/HydraNet-WikiSQL/blob/8436d3bfece23b63017a3adabbfd6e7b00e4b23c/utils.py#L31

https://github.com/lyuqin/HydraNet-WikiSQL/blob/8436d3bfece23b63017a3adabbfd6e7b00e4b23c/utils.py#L42

As long as the pretrained model is supported by Huggingface API, it should be straightforward to add and use.

Note that pretrained models could have subtle difference in tokenization, and you probably need to manually change the format and code to get a good result. You can find one example here, where the code is slightly different for BERT vs RoBERTa:
https://github.com/lyuqin/HydraNet-WikiSQL/blob/8436d3bfece23b63017a3adabbfd6e7b00e4b23c/featurizer.py#L82
