### ISSUE TITLE
Is there any Issue on accuracy score on EG cases ?

### ISSUE THREAD

**Issue by jskim0406** [lyuqin/HydraNet-WikiSQL#7]
I really appreciate your code and model(HydraNet). with your code, I can study and understand a lot. Thank you.

But I have a problem with accuracy score on EG cases.
Is there any issue or report on accuracy score on EG cases ?

I just change batch_size because of my CUDA memory limit. But I do not change any line.
I can get right accuracy scores in no EG cases. But, in EG cases.. I have very low (abnormal) accuracy scroe..

For example, when I open the "output/test_out.jsonl.eg", 
then "conds : [ ]" of all predicted quries have empty list.

So, I get 0.00825.. score in wcn_acc, wcc_acc, wco_acc, wcv_acc metrics.

Debugging is on me. but, if you give me some advice, It will be very helpful ! :)

Thank you!

**Comment by lyuqin** [comment]
Can you double check the environment, especially "sqlalchemy==1.3.23" as specified in the requirements.txt? In EG mode, model needs to call dbengine and execute sql, and it seems that the execution in your case failed. You can debug and set break point at 
https://github.com/lyuqin/HydraNet-WikiSQL/blob/afdf1e5c32a5259bc926e7d3f095e06019eaef6d/modeling/base_model.py#L83
to see if any bug in the returned results.

**Comment by lyuqin** [comment]
I recommend to run experiment using docker image built with the Dockerfile in repo. Please refer to readme for the detail.
