### ISSUE TITLE
Question about Ranking score in your code

### ISSUE THREAD

**Issue by jskim0406** [lyuqin/HydraNet-WikiSQL#8]
Hi!
With your feedback on issue#7, I can experiment safely hydra-net with your code.
I really appreciate it 👍 

Recently I am focusing on Semantic parsing task(especially, Text-to-SQL).
So I am doing some experiments with several models on Wiki-SQL dataset.
and now I am trying to get 'Top-k accuracy' on Predicted SQL query output of Hydra-net.

I am graduate student,, So my question would be a little-bit bothersome.. I understand :(
Nevertheless, let me begin my question .. ! 

In your model, I understand that 'Ranking' is very important.
So, I am trying to get "where can I find and get ranking scores ..!?"

My brain says "you can find ranking scores in this line...!"..
SELECT ranking score is 'select_id_prob'
https://github.com/lyuqin/HydraNet-WikiSQL/blob/afdf1e5c32a5259bc926e7d3f095e06019eaef6d/modeling/base_model.py#L169

and WHERE ranking score is 'where_id_prob'
https://github.com/lyuqin/HydraNet-WikiSQL/blob/afdf1e5c32a5259bc926e7d3f095e06019eaef6d/modeling/base_model.py#L136

Is my guess right..!?
It is very basic and elementary question for you. But it will be very helpful for me : )

Thank you for reading me.

**Comment by lyuqin** [comment]
Yes it's correct. In addition to that, `model_output["column_func"][:, 2]` is irrelvance ranking score.
